name: Secret Scan Using TruffleHog

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions: {} # No additional permissions needed

jobs:
  trufflehog:
    name: TruffleHog OSS Secret Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          scanArguments: --fail --no-update --json .
